version: '2'
services:
    http:
        build: http/.
        command: http-server . -p 80
        depends_on: 
            - ror
        #ports:
        #    - "8001:80"
        volumes:
            - ./http/:/http
            - /http/node_modules
        restart: always
        networks:
            - nginx_default
networks:
    nginx_default:
        external: true
